import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body
        className={` antialiased`}
      >
        <AuthProvider>
          <Header />
          <main>
            {children}
            <ToastContainer />
          </main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
